insert into "SAP_HANA_TUTORIAL_ADV"."SALES" values(100,1,100);
insert into "SAP_HANA_TUTORIAL_ADV"."SALES" values(100,2,90);
insert into "SAP_HANA_TUTORIAL_ADV"."SALES" values(100,5,85);
insert into "SAP_HANA_TUTORIAL_ADV"."SALES" values(200,2,80);
insert into "SAP_HANA_TUTORIAL_ADV"."SALES" values(200,1,75);
insert into "SAP_HANA_TUTORIAL_ADV"."SALES" values(300,3,85);
insert into "SAP_HANA_TUTORIAL_ADV"."SALES" values(400,4,75);
insert into "SAP_HANA_TUTORIAL_ADV"."SALES" values(500,1,65);
insert into "SAP_HANA_TUTORIAL_ADV"."SALES" values(500,2,65);